<?xml version="1.0"?>
<robot name="Test_Bench" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Test Bench Properties-->
    <xacro:property name="test_rect_width" value=".5"/>
    <xacro:property name="test_rect_length" value=".5"/>
    <xacro:property name="test_rect_height" value=".5"/>
    <xacro:property name="cart_width" value="1.2"/>
    <xacro:property name="cart_length" value=".6"/>
    <xacro:property name="cart_height" value=".5"/>

    <xacro:property name="wheel_radius" value="0.10"/>
    <xacro:property name="wheel_width" value="0.04"/>
    <xacro:property name="wheel_offset" value=".1"/>

    <!-- Bench Base-->
    <link name="base_link">
        
    </link>

    <!-- Cart and Bench Footprint-->
    <link name="cart_footprint" type="fixed">
        <visual>
            <geometry>
                <box size="${cart_length} ${cart_width} ${cart_height}"/>
            </geometry>
            <material name="Cyan">
                <color rgba="0 1.0 1.0 1.0"/>
            </material>
        </visual>
    </link>
    <joint name="cart_joint" type="fixed">
        <parent link="base_link"/>
        <child link="cart_footprint"/>
        <origin xyz="0.0 0.0 ${-(wheel_radius+wheel_offset)}" rpy="0 0 0"/>
    </joint>

    <link name="bench_footprint" type="fixed">
        <visual>
            <geometry>
                <box size="${test_rect_length} ${test_rect_width} ${test_rect_height}"/>
            </geometry>
            <material name="Cyan">
                <color rgba="0 1.0 1.0 1.0"/>
            </material>
        </visual>
    </link>
    <joint name="bench_joint" type="fixed">
        <parent link="cart_footprint"/>
        <child link="bench_footprint"/>
        <origin xyz="0.0 0.0 ${-(cart_height)}" rpy="0 0 0"/>
    </joint>

</robot>