<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Test Bench Properties-->
    <xacro:property name="bench_width" value="1.2"/>
    <xacro:property name="bench_length" value=".6"/>
    <xacro:property name="bench_height" value=".5"/>

    <xacro:property name="wheel_radius" value="0.10"/>
    <xacro:property name="wheel_width" value="0.04"/>
    <xacro:property name="wheel_offset" value=".1"/>

    <!-- Base Link, this is our origin point for all test bench joints-->
    <link name="base_link">

    </link>

    <!-- Bench Footprint-->
    <link name="bench_footprint" type="fixed">
        <visual>
            <geometry>
                <box size="${bench_length} ${bench_width} ${bench_height}"/>
            </geometry>
            <material name="Cyan">
                <color rgba="0 1.0 1.0 1.0"/>
            </material>
        </visual>
    </link>
    <joint name="bench_joint" type="fixed">
        <parent link="base_link"/>
        <child link="bench_footprint"/>
        <origin xyz="0.0 0.0 ${(wheel_radius*2+wheel_offset)}" rpy="0 0 0"/>
    </joint>

</robot>